-- AUTO-GENERATED by scripts/generate_ddl.py
-- Do NOT edit manually. Regenerate with: uv run generate --city <city>
--
-- Creates 7 Iceberg tables in the 'streetlights' schema.
-- These tables are the storage layer for pg_lake → Snowflake CLD sync.

SET search_path TO streetlights, public;

-- Drop existing tables (reverse dependency order)
DROP TABLE IF EXISTS streetlights.power_grid_zones CASCADE;
DROP TABLE IF EXISTS streetlights.demographics CASCADE;
DROP TABLE IF EXISTS streetlights.weather_enrichment CASCADE;
DROP TABLE IF EXISTS streetlights.light_sensors CASCADE;
DROP TABLE IF EXISTS streetlights.energy_consumption CASCADE;
DROP TABLE IF EXISTS streetlights.maintenance_records CASCADE;
DROP TABLE IF EXISTS streetlights.street_lights CASCADE;

-- Table 1: street_lights
CREATE TABLE IF NOT EXISTS streetlights.street_lights (
    id INTEGER,
    pole_id TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    neighborhood TEXT,
    install_date DATE,
    wattage INTEGER,
    light_type TEXT,
    status TEXT
) USING iceberg;

-- Table 2: maintenance_records
CREATE TABLE IF NOT EXISTS streetlights.maintenance_records (
    id INTEGER,
    light_id INTEGER NOT NULL,
    date DATE NOT NULL,
    type TEXT,
    description TEXT,
    cost NUMERIC(10,2),
    technician TEXT
) USING iceberg;

-- Table 3: energy_consumption
CREATE TABLE IF NOT EXISTS streetlights.energy_consumption (
    id INTEGER,
    light_id INTEGER NOT NULL,
    date DATE NOT NULL,
    hour INTEGER NOT NULL,
    kwh NUMERIC(8,4),
    voltage NUMERIC(5,1),
    power_factor NUMERIC(4,3)
) USING iceberg;

-- Table 4: light_sensors
CREATE TABLE IF NOT EXISTS streetlights.light_sensors (
    id INTEGER,
    light_id INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    lux NUMERIC(7,1),
    motion_detected BOOLEAN,
    temperature NUMERIC(4,1)
) USING iceberg;

-- Table 5: weather_enrichment
CREATE TABLE IF NOT EXISTS streetlights.weather_enrichment (
    date DATE,
    season TEXT NOT NULL,
    temperature NUMERIC(5,1),
    humidity NUMERIC(5,1),
    wind_speed NUMERIC(5,1),
    precipitation NUMERIC(5,1)
) USING iceberg;

-- Table 6: demographics
CREATE TABLE IF NOT EXISTS streetlights.demographics (
    neighborhood TEXT,
    population INTEGER,
    median_income INTEGER,
    commercial_pct NUMERIC(3,2)
) USING iceberg;

-- Table 7: power_grid_zones
CREATE TABLE IF NOT EXISTS streetlights.power_grid_zones (
    zone_id TEXT,
    zone_name TEXT NOT NULL,
    capacity_kw INTEGER,
    current_load_kw INTEGER,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
) USING iceberg;

-- Verification
DO $$
DECLARE
    tbl_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO tbl_count
    FROM information_schema.tables
    WHERE table_schema = 'streetlights'
      AND table_type = 'FOREIGN';

    RAISE NOTICE 'Iceberg tables created: % tables', tbl_count;
END $$;
