"""Generate Iceberg DDL from CSV column definitions.

TABLE_SCHEMAS is the single source of truth mapping CSV filenames to their
PostgreSQL Iceberg table definitions. Other modules (gate.py dry-run,
generate_all.py) import from here.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# TABLE_SCHEMAS: csv_filename → (table_name, [(col, pg_type, constraints)])
# ---------------------------------------------------------------------------

TABLE_SCHEMAS: dict[str, tuple[str, list[tuple[str, str, str]]]] = {
    "street_lights.csv": (
        "street_lights",
        [
            ("id", "INTEGER", "PRIMARY KEY"),
            ("pole_id", "TEXT", "NOT NULL"),
            ("latitude", "DOUBLE PRECISION", "NOT NULL"),
            ("longitude", "DOUBLE PRECISION", "NOT NULL"),
            ("neighborhood", "TEXT", ""),
            ("install_date", "DATE", ""),
            ("wattage", "INTEGER", ""),
            ("light_type", "TEXT", ""),
            ("status", "TEXT", ""),
        ],
    ),
    "maintenance_records.csv": (
        "maintenance_records",
        [
            ("id", "INTEGER", "PRIMARY KEY"),
            ("light_id", "INTEGER", "NOT NULL"),
            ("date", "DATE", "NOT NULL"),
            ("type", "TEXT", ""),
            ("description", "TEXT", ""),
            ("cost", "NUMERIC(10,2)", ""),
            ("technician", "TEXT", ""),
        ],
    ),
    "energy_consumption.csv": (
        "energy_consumption",
        [
            ("id", "INTEGER", "PRIMARY KEY"),
            ("light_id", "INTEGER", "NOT NULL"),
            ("date", "DATE", "NOT NULL"),
            ("hour", "INTEGER", "NOT NULL"),
            ("kwh", "NUMERIC(8,4)", ""),
            ("voltage", "NUMERIC(5,1)", ""),
            ("power_factor", "NUMERIC(4,3)", ""),
        ],
    ),
    "light_sensors.csv": (
        "light_sensors",
        [
            ("id", "INTEGER", "PRIMARY KEY"),
            ("light_id", "INTEGER", "NOT NULL"),
            ("timestamp", "TIMESTAMP", "NOT NULL"),
            ("lux", "NUMERIC(7,1)", ""),
            ("motion_detected", "BOOLEAN", ""),
            ("temperature", "NUMERIC(4,1)", ""),
        ],
    ),
    "weather_enrichment.csv": (
        "weather_enrichment",
        [
            ("date", "DATE", "PRIMARY KEY"),
            ("season", "TEXT", "NOT NULL"),
            ("temperature", "NUMERIC(5,1)", ""),
            ("humidity", "NUMERIC(5,1)", ""),
            ("wind_speed", "NUMERIC(5,1)", ""),
            ("precipitation", "NUMERIC(5,1)", ""),
        ],
    ),
    "demographics.csv": (
        "demographics",
        [
            ("neighborhood", "TEXT", "PRIMARY KEY"),
            ("population", "INTEGER", ""),
            ("median_income", "INTEGER", ""),
            ("commercial_pct", "NUMERIC(3,2)", ""),
        ],
    ),
    "power_grid_zones.csv": (
        "power_grid_zones",
        [
            ("zone_id", "TEXT", "PRIMARY KEY"),
            ("zone_name", "TEXT", "NOT NULL"),
            ("capacity_kw", "INTEGER", ""),
            ("current_load_kw", "INTEGER", ""),
            ("latitude", "DOUBLE PRECISION", ""),
            ("longitude", "DOUBLE PRECISION", ""),
        ],
    ),
}

# Canonical table order (matches CSV generation order in generate_all.py)
TABLE_ORDER = [
    "street_lights",
    "maintenance_records",
    "energy_consumption",
    "light_sensors",
    "weather_enrichment",
    "demographics",
    "power_grid_zones",
]


def _render_create_table(table_name: str, columns: list[tuple[str, str, str]]) -> str:
    """Render a single CREATE TABLE ... USING iceberg statement.

    Note: PRIMARY KEY constraints are not supported on Iceberg (foreign) tables
    in pg_lake, so they are stripped from the DDL output.
    """
    lines = []
    lines.append(f"CREATE TABLE IF NOT EXISTS streetlights.{table_name} (")
    col_defs = []
    for col, dtype, constraint in columns:
        parts = [f"    {col}", dtype]
        # Strip PRIMARY KEY — not supported on pg_lake Iceberg (foreign) tables
        if constraint and constraint.upper() != "PRIMARY KEY":
            parts.append(constraint)
        col_defs.append(" ".join(parts))
    lines.append(",\n".join(col_defs))
    lines.append(") USING iceberg;")
    return "\n".join(lines)


def generate_iceberg_ddl(output_path: Path | None = None) -> str:
    """Generate init/02_create_iceberg_tables.sql content.

    If output_path is provided, writes the file. Always returns the SQL string.
    """
    sections = []

    # Header
    sections.append(
        "-- AUTO-GENERATED by scripts/generate_ddl.py\n"
        "-- Do NOT edit manually. Regenerate with: uv run generate --city <city>\n"
        "--\n"
        "-- Creates 7 Iceberg tables in the 'streetlights' schema.\n"
        "-- These tables are the storage layer for pg_lake → Snowflake CLD sync.\n"
    )

    # Set search path
    sections.append("SET search_path TO streetlights, public;\n")

    # Drop existing tables in reverse order
    sections.append("-- Drop existing tables (reverse dependency order)")
    for table_name in reversed(TABLE_ORDER):
        sections.append(f"DROP TABLE IF EXISTS streetlights.{table_name} CASCADE;")
    sections.append("")

    # Create tables
    for i, table_name in enumerate(TABLE_ORDER, 1):
        # Find the schema entry for this table
        csv_file = next(csv for csv, (tbl, _) in TABLE_SCHEMAS.items() if tbl == table_name)
        _, columns = TABLE_SCHEMAS[csv_file]

        sections.append(f"-- Table {i}: {table_name}")
        sections.append(_render_create_table(table_name, columns))
        sections.append("")

    # Verification block
    sections.append("-- Verification")
    sections.append("DO $$")
    sections.append("DECLARE")
    sections.append("    tbl_count INTEGER;")
    sections.append("BEGIN")
    sections.append("    SELECT COUNT(*) INTO tbl_count")
    sections.append("    FROM information_schema.tables")
    sections.append("    WHERE table_schema = 'streetlights'")
    sections.append("      AND table_type = 'FOREIGN';")
    sections.append("")
    sections.append("    RAISE NOTICE 'Iceberg tables created: % tables', tbl_count;")
    sections.append("END $$;")

    sql = "\n".join(sections) + "\n"

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(sql, encoding="utf-8")

    return sql


def get_dry_run_step3() -> str:
    """Return formatted dry-run output for step-3."""
    lines = []
    lines.append("Step 3: Create Schema + Load Data")
    lines.append("=" * 40)
    lines.append("")
    lines.append("Actions:")
    lines.append("  1. Enable extensions (pg_lake, PostGIS)")
    lines.append("  2. Create schema: streetlights")
    lines.append("  3. Create 7 Iceberg tables")
    lines.append("  4. Load CSV data via \\copy")
    lines.append("")
    lines.append("Tables to create:")
    for i, table_name in enumerate(TABLE_ORDER, 1):
        csv_file = next(csv for csv, (tbl, _) in TABLE_SCHEMAS.items() if tbl == table_name)
        _, columns = TABLE_SCHEMAS[csv_file]
        col_names = [c[0] for c in columns]
        lines.append(f"  {i}. streetlights.{table_name}")
        lines.append(f"     CSV: data/{csv_file}")
        lines.append(f"     Columns: {', '.join(col_names)}")
        lines.append("")
    lines.append("CSV → Table mapping:")
    for csv_file, (table_name, _) in TABLE_SCHEMAS.items():
        lines.append(f"  data/{csv_file} → streetlights.{table_name}")
    return "\n".join(lines)


if __name__ == "__main__":
    # Standalone: generate and print DDL
    sql = generate_iceberg_ddl()
    print(sql)
